baseURL = 'https://rstumpner.github.io/pieces/'
languageCode = 'en-us'
title = 'Pieces'
theme = 'Papermod'
uglyURLs = true

[menu]
[[menu.main]]
  name = 'Home'
  pageRef = '/'
  weight = 10
[[menu.main]]
  name = 'Challenges'
  pageRef = '/vergabe.html'
  weight = 20
[[menu.main]]
  name = 'Q & A'
  pageRef = '/QA.html'
  weight = 30

[markup.goldmark.renderer]
  unsafe = true # Allow HTML in md files